2021-01-01 11:39:05|ERROR|Home.getNearby|PDOException: The user specified as a definer ('livenew'@'127.0.0.1') does not exist in /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php:258
Stack trace:
#0 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(811): NotORM_Result->query('SELECT uid,titl...', Array)
#1 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(896): NotORM_Result->execute()
#2 /www/wwwroot/yunbao.com/PhalApi/Appapi/Model/Home.php(285): NotORM_Result->fetchAll()
#3 /www/wwwroot/yunbao.com/PhalApi/Appapi/Domain/Home.php(61): Model_Home->getNearby('0.0', '0.0', '1')
#4 /www/wwwroot/yunbao.com/PhalApi/Appapi/Api/Home.php(537): Domain_Home->getNearby('0.0', '0.0', '1')
#5 /www/wwwroot/yunbao.com/PhalApi/PhalApi/PhalApi.php(57): Api_Home->getNearby()
#6 /www/wwwroot/yunbao.com/public/appapi/index.php(15): PhalApi->response()
#7 {main}
2021-01-01 13:18:53|DEBUG|succeed to upload file to UCloud_Engine_Local|https://www.qingwazb.com/upload///thumb/20210101/06628223339514815.png
2021-01-01 16:57:07|DEBUG|succeed to upload file to UCloud_Engine_Local|https://www.qingwazb.com/upload///thumb/20210101/06628354272011630.png
2021-01-01 16:58:59|DEBUG|succeed to upload file to UCloud_Engine_Local|https://www.qingwazb.com/upload///avatar/20210101/06628355393812531.png
2021-01-01 17:23:22|DEBUG|succeed to upload file to UCloud_Engine_Local|https://www.qingwazb.com/upload///thumb/20210101/06628370026859395.png
2021-01-01 18:25:44|DEBUG|succeed to upload file to UCloud_Engine_Local|https://www.qingwazb.com/upload///thumb/20210101/06628407444826539.png
